### ISSUE TITLE
클래스 템플릿화, cpp 파일 삭제(6)

### ISSUE THREAD

**Issue by SoohanBae** [wnsgml972/cppBasic#12]
https://github.com/SoohanBae/cppBasic/commit/3271fd4464192ff4a61da4625084a85b6607061c
다음 작업으로 제가 짜놓은 변수명, 클래스 명, 구조를 재정비하려고 합니다.

템플릿 typename에도 이름짓기 규칙이 있는지, 있으면 어떻게 짜면 좋은지 궁금합니다.

**Comment by wnsgml972** [comment]
*Data, *Info 등 표현력이 애매한 단어를 사용하지 않고, 해당 Type을 표현하기에 적절한 단어를 사용하여 template 변수를 표현하시면 될 것 같습니다.
