### ISSUE TITLE
변수명, 함수명 리팩토링(7)

### ISSUE THREAD

**Issue by SoohanBae** [wnsgml972/cppBasic#13]
typename에 대한 고민을 해보고 있지만, 변수명이 data여서 아무리 생각해도 typedata 밖에 떠오르지 않네요.

**Comment by wnsgml972** [comment]
TypeElement라는 명칭은 어떻게 생각하세요??

**Comment by wnsgml972** [comment]
ElementType, TypeElement 둘 다 좋을 것 같습니다.

**Comment by SoohanBae** [comment]
마침 ElementType으로 바꾸려고 하던 참입니다. 좋다고 생각해요!
