### ISSUE TITLE
vector 파일 구현 및, 검증(1)

### ISSUE THREAD

**Issue by SoohanBae** [wnsgml972/cppBasic#6]
https://github.com/SoohanBae/cppBasic/commit/b0b66890ee5a0ffbab53dd4aaa4664903afa217c

vector 파일 구현 후 커밋입니다.
제가 짜고 있는 코드 및 진행 방법이 cppBasic 프로젝트의 방향성에 맞는지도 확인 부탁드립니다.

질문점

"삽입되는 데이터를 표준 입력으로 받음" -  'std::cin>>' 으로 받아야 하는 것인가요? 
"상속을 통해 기반 클래스는 동일하게 구현" - 자세한 설명 부탁드립니다.

**Comment by wnsgml972** [comment]
1. 질문 : "제가 짜고 있는 코드 및 진행 방법이 cppBasic 프로젝트의 방향성에 맞는지도 확인 부탁드립니다."
답변 : 큰 흐름은 잘 잡고 계신 것 같습니다. 자세한 코드 리뷰는 첫 번째 과제가 끝난 뒤 진행하도록 하겠습니다.

2. 질문 : "삽입되는 데이터를 표준 입력으로 받음" - 'std::cin>>' 으로 받아야 하는 것인가요?"
답변 : 다른 것을 사용하셔도 괜찮고, 간단하게 std::cin으로 받으셔도 괜찮습니다.

3. 질문 : "상속을 통해 기반 클래스는 동일하게 구현" - 자세한 설명 부탁드립니다."
답변 : 추 후 DataManager에 의하여 생성/삭제되는 Vector와 List를 하나의 컨테이너로 관리하기 위하여 Vector와 List의 기반 클래스를 같게 하여, DataManager가 하나의 변수로 2가지 자료구조를 관리하기 위함입니다.
