### ISSUE TITLE
Vector/List 템플릿 구현에 관한 질문

### ISSUE THREAD

**Issue by SoohanBae** [wnsgml972/cppBasic#9]
"파일 입력을 활용한 데이터 삽입 기능
파일 출력을 통한 데이터 정보 출력 기능"
 
iostream을 활용해 .txt 파일을 통해 데이터를 입력하고 .txt파일로 출력하는 기능을 추가하면 되는건가요?

그리고 이슈 라벨을 달고 싶은데 권한이 없네요 ㅠㅠ

**Comment by wnsgml972** [comment]
넵넵 맞습니다.

권한 메일 보냈습니다!
